"""initial schema: research, auth and financial data store

Revision ID: 6fd2e485196b
Revises: 
Create Date: 2026-09-30 17:18:34.626434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fd2e485196b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # pgvector powers search-by-meaning over document text (Postgres only).
    # Created only where the server offers it: no table uses a vector column
    # yet, so a managed Postgres without pgvector must not fail the migration.
    bind = op.get_bind()
    if bind.dialect.name == "postgresql" and bind.exec_driver_sql(
            "SELECT 1 FROM pg_available_extensions WHERE name = 'vector'").first():
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('claim_id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_research_run_id'), ['research_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_verification_status'), ['verification_status'], unique=False)

    op.create_table('companies',
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('industry_id', sa.String(), nullable=True),
    sa.Column('tier', sa.String(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('company_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_industry_id'), ['industry_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_companies_symbol'), ['symbol'], unique=True)

    op.create_table('conflicts',
    sa.Column('conflict_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('is_genuine_conflict', sa.Boolean(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('conflict_id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_entity'), ['entity'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_conflicts_research_run_id'), ['research_run_id'], unique=False)

    op.create_table('evidence',
    sa.Column('evidence_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('evidence_id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_research_run_id'), ['research_run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_source_id'), ['source_id'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stats', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_kind'), ['kind'], unique=False)

    op.create_table('reports',
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_research_run_id'), ['research_run_id'], unique=True)

    op.create_table('research_runs',
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('research_run_id')
    )
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_runs_status'), ['status'], unique=False)

    op.create_table('sessions',
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('sources',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_tier', sa.String(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('source_id')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_research_run_id'), ['research_run_id'], unique=False)

    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), server_default='viewer', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('verification_results',
    sa.Column('verification_id', sa.String(), nullable=False),
    sa.Column('research_run_id', sa.String(), nullable=False),
    sa.Column('claim_id', sa.String(), nullable=False),
    sa.Column('final_verdict', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('verification_id')
    )
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_results_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_final_verdict'), ['final_verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_results_research_run_id'), ['research_run_id'], unique=False)

    op.create_table('documents',
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('consolidated', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('checksum', sa.String(), nullable=False),
    sa.Column('filed_at', sa.DateTime(), nullable=True),
    sa.Column('audited', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('notes', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('checksum')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index('ix_documents_company_type_period', ['company_id', 'doc_type', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_doc_type'), ['doc_type'], unique=False)

    op.create_table('financial_facts',
    sa.Column('fact_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('period_type', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('consolidated', sa.Boolean(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fact_id'),
    sa.UniqueConstraint('document_id', 'metric', 'period_type', 'period_end', name='uq_fact_per_document')
    )
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.create_index('ix_facts_lookup', ['company_id', 'metric', 'period_type', 'period_end'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_facts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_financial_facts_document_id'), ['document_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_facts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_facts_document_id'))
        batch_op.drop_index(batch_op.f('ix_financial_facts_company_id'))
        batch_op.drop_index('ix_facts_lookup')

    op.drop_table('financial_facts')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_doc_type'))
        batch_op.drop_index('ix_documents_company_type_period')
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    with op.batch_alter_table('verification_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_results_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_verification_results_final_verdict'))
        batch_op.drop_index(batch_op.f('ix_verification_results_claim_id'))

    op.drop_table('verification_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_research_run_id'))

    op.drop_table('sources')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('research_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_runs_status'))

    op.drop_table('research_runs')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_research_run_id'))

    op.drop_table('reports')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_kind'))

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_source_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_evidence_claim_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_conflicts_metric'))
        batch_op.drop_index(batch_op.f('ix_conflicts_entity'))

    op.drop_table('conflicts')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_symbol'))
        batch_op.drop_index(batch_op.f('ix_companies_industry_id'))

    op.drop_table('companies')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_verification_status'))
        batch_op.drop_index(batch_op.f('ix_claims_source_id'))
        batch_op.drop_index(batch_op.f('ix_claims_research_run_id'))
        batch_op.drop_index(batch_op.f('ix_claims_metric'))
        batch_op.drop_index(batch_op.f('ix_claims_entity'))

    op.drop_table('claims')
    # ### end Alembic commands ###
